### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by CarboSauce** [raxonpc/sjpp#3]
Leak when exception is thrown in the ctor of SjpApi implementation
https://github.com/raxonpc/sjpp/blob/4d56cb96001c0cec716c50ab094f252d0b46b504/src/sjpp.cpp#L19

**Comment by raxonpc** [comment]
> Leak when exception is thrown in the ctor of SjpApi implementation
> https://github.com/raxonpc/sjpp/blob/4d56cb96001c0cec716c50ab094f252d0b46b504/src/sjpp.cpp#L19

💀💀💀

**Comment by raxonpc** [comment]
Fixed
